import React from "react";
import "./Nrgyon.css";

import Vector493 from "../images/Vector493.png";
import Line26 from "../images/Line26.png";
import ETHEREUM from "../images/ETHEREUM.png";
import Elli344 from "../images/Elli344.png";
import Elli343 from "../images/Elli343.png";
import Elli346 from "../images/Elli346.png";
import Ellipse180 from "../images/Ellipse180.png";
function Nrgyon() {
  return (
    <>
      <div className="Nrgyon">
        <div className="container-4">
          <div class="position-absolute start-0">
            <img className="V493" src={Vector493} alt="" />
          </div>
          <div className="row count-2">
            <div className="col-md-4 col-xs-6 col-sm-12 c-count-1">
              <div>
                <span className="N2N-span-1 position-relative">
                  NRGY on
                  <br className="mobile40" /> ETHEREUM
                </span>
                <br className="mobile40" />
                <span className="pt-5 N2N-span-3">
                  The NRGY DeFi coin is our foundational currency that
                  <br className="mobile40" />
                  provides functional liquidity for the NRGY economy and
                  <br className="mobile40" /> is used to collect royalties
                  generated by the financial
                  <br className="mobile40" /> system.
                </span>
                <div class="position-absolute start-0 ">
                  <img className="etih-rin" src={ETHEREUM} alt="" />
                </div>
                <span className="N2N-span-3">
                  Staking NRGY produces weekly minting rewards for
                  <br className="mobile40" /> stakers. NRGY is the only staking
                  contract that gives
                  <br className="mobile40" />
                  access to royalties and incentivized referral rewards.
                </span>
              </div>

              <div className="container-5">
                <div class="position-absolute start-0">
                  <img className="Elli344-N2N" src={Elli344} alt="" />
                </div>
                <div className="card bg-N2N2-2">
                  <div className="row">
                    <span className="min-5">Coin Holder Rewards</span>
                    <div className="col-md-4 col-sm-12 col-xs-12 gapp-09">
                      <span className="min-4">4%</span>
                      <br />
                      <span className="min-5">Transaction Rewards</span>
                      <br />
                      <span className="min-6">
                        For NRGYGO holders recieved in BNB & NRGYGO Coins
                      </span>
                    </div>
                    {/* <div class="position-absolute">
                      <img className="V495" src={Line26} alt="" />
                    </div> */}
                    <div className="col-md-4 col-sm-12 col-xs-12 gapp-09">
                      <div className="line456">
                        <span className="min-4 m-gapp">20%</span>
                        <br />
                        <span className="min-5 m-gapp">
                          NRGY Staker{" "}
                          <span className="min-5 m-gapp">Rewards</span>
                        </span>
                        <br className="m-gapp" />
                        <div className="m-gapp">
                          <span className="min-6">
                            For NRGY stakers holding 5 coins or more received
                            <br className="m-gapp" /> in USDC
                          </span>
                        </div>
                      </div>
                    </div>
                    {/* <div class="position-absolute">
                      <img className="V496" src={Line26} alt="" />
                    </div> */}

                    <div className="col-md-4 col-sm-12 col-xs-12 gapp-09">
                      <div className="line456">
                        <span className="min-4 m-gapp">25%</span>
                        <br />

                        <span className="min-5 m-gapp">
                          NRGY Liquidity <br />
                          <span className="min-5 m-gapp">Pool</span>
                        </span>

                        <br className="" />
                        <div className="m-gapp">
                          <span className="min-6 ">
                            Increase liquidity of NRGY/USDC trading pair on
                            uniswap
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="pt-3 btn-34">
                    <button class="btn  btn-get-nrgy-3" type="submit">
                      <span className="N2N-font">GET $NRGYGO</span>
                    </button>
                  </div>
                </div>
              </div>
              <div class="position-absolute start-0">
                <img className="play-none" src={Ellipse180} alt="" />
              </div>
              <span className="total-suppl">Total Supply - 4.300.000</span>
            </div>

            <div className="col-md-4 col-md-6 col-xs-12 col-sm-12 col-N2N-2">
              <div>
                <span className="N2N-span-1 N_BINANCE">
                  NRGYGO on
                  <img
                    className="position-absolute pin-ball"
                    src={Elli346}
                    alt=""
                  />
                  <br className="mobile40" />
                    BINANCE SMART
                  <br className="mobile40" />
                  CHAIN
                </span>
                <br className="mobile40" />
                {/* choti ball */}

                <span className="N2N-span-3">
                  NRGYGO coin on binance smart chain is our new
                  <br className="mobile40" /> low-cost transactional coin
                  designed to provide
                  <br className="mobile40" />
                  convebience for DAPP consumers while producting
                  <br className="mobile40" />
                  long-term prepetual rewards for the NRGY economy.
                </span>
                <br className="mobile40" />

                <span className="N2N-span-3">
                  NRGYGO provides great opportunities for crypto
                  <br className="mobile40" /> investors throught trading and new
                  income
                  <br className="mobile40" />
                  opportunities for the NRGY community throught shared
                  <br className="mobile40" />
                  free rewards.
                </span>
                <br className="mobile40" />
                <span className="N2N-span-3">NRGYGO Convensions:</span>
                <br className="mobile40" />
              </div>
              <span className="N2N-span-3">
                <span class="NGRYGO_A2A">1,000,000 NRGYGO = 1 NRGY</span>
              </span>
              <div class="position-absolute end-0">
                <img className="elli-344-ikm" src={Elli344} alt="" />
              </div>
              <div className="container-6">
                <div className="card bg-N2N2-2">
                  <div className="row">
                    <span className="min-5">Coin Holder Rewards</span>
                    <div className="col-md-4 col-sm-12 col-xs-12 gapp-09">
                      <span className="min-4">1%</span>
                      <br />
                      <span className="min-5">Transaction Rewards</span>
                      <br />
                      <span className="min-6">
                        For NRGYGO holders recieved in BNB & NRGYGO Coins
                      </span>
                    </div>
                    {/* <div class="position-absolute">
                      <img className="V495" src={Line26} alt="" />
                    </div> */}
                    <div className="col-md-4 col-sm-12 col-xs-12 gapp-09">
                      <div className="line456">
                        <span className="min-4 m-gapp">0.5%</span>
                        <br />
                        <span className="min-5 m-gapp">
                          NRGY Staker{" "}
                          <span className="min-5 m-gapp">Rewards</span>
                        </span>
                        <br className="m-gapp" />
                        <div className="m-gapp">
                          <span className="min-6">
                            For NRGY stakers holding 5 coins or more received
                            <br className="m-gapp" /> in USDC
                          </span>
                        </div>
                      </div>
                    </div>
                    {/* <div class="position-absolute">
                      <img className="V496" src={Line26} alt="" />
                    </div> */}

                    <div className="col-md-4 col-sm-12 col-xs-12 gapp-09">
                      <div className="line456">
                        <span className="min-4 m-gapp">0.5%</span>
                        <br />

                        <span className="min-5 m-gapp">
                          NRGY Liquidity <br />
                          <span className="min-5 m-gapp">Pool</span>
                        </span>

                        <br className="" />
                        <div className="m-gapp">
                          <span className="min-6 ">
                            Increase liquidity of NRGY/USDC trading pair on
                            uniswap
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="pt-3 btn-34">
                    <button class="btn  btn-get-nrgy-3" type="submit">
                      <span className="N2N-font">GET $NRGYGO</span>
                    </button>
                  </div>
                </div>
              </div>
              <div className="btn-45">
                <span className="pt-3 total-supply">
                  Total Supply - 10,000,000,000
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
export default Nrgyon;
