import React from "react";
import "./Nrgyon.css";
import NRGY from "../images/NRGY.png";
import Vector493 from "../images/Vector493.png";
import Line26 from "../images/Line26.png";
import ETHEREUM from "../images/ETHEREUM.png";
import Elli344 from "../images/Elli344.png";
import Elli343 from "../images/Elli343.png";
import Elli346 from "../images/Elli346.png";
import Ellipse180 from "../images/Ellipse180.png";
function Nrgyon() {
  return (
    <>
      <div className="Nrgyon">
        <div className="container-4">
          <div class="position-absolute start-0">
            <img className="V493" src={Vector493} alt="" />
          </div>
          <div className="row count-1">
            <div className="col-4 col-xs-4 c-count-1">
              <div>
                <span className="N2N-span-1 position-relative">
                  NRGY on
                  <br /> ETHEREUM
                </span>
                <br />
                <span className="pt-5 N2N-span-3">
                  The NRGY DeFi coin is our foundational currency that
                  <br />
                  provides functional liquidity for the NRGY economy and
                  <br /> is used to collect royalties generated by the financial
                  <br /> system.
                </span>

                <span className="N2N-span-3">
                  Staking NRGY produces weekly minting rewards for
                  <br /> stakers. NRGY is the only staking contract that gives
                  <br />
                  access to royalties and incentivized referral rewards.
                </span>
              </div>

              <div className="container-5">
              <div class="position-absolute start-0">
            <img className="Elli344-N2N" src={Elli344} alt="" />
          </div>
                <div className="card bg-N2N2">
                  <div className="row">
                    <span className='min-5'>Staking Rewards</span>
                    <div className="col-4">
               
                      <span className="min-4">4%</span><br/>
                      <span className="min-5">Minting Reward Target</span><br/>
                      <span className="min-6">
                        For NRGY stakers over 100 week Minting Schedule
                      </span>
                    </div>
                    <div class="position-absolute">
                      <img className="V493" src={Line26} alt="" />
                    </div>
                    <div className="col-4">
                      <span className="min-4">20%</span><br/>
                      <span className="min-5">DApp Royalty Rewards</span><br/>
                      <span className="min-6">
                      For NRGY stakers over 100 week Minting Schedule
                      </span>
                    </div>
                    <div class="position-absolute">
                      <img className="V494" src={Line26} alt="" />
                    </div>
                    <div className="col-4">
                      <span className="min-4">25%</span><br/>
                      <span  className="min-5">Builder Referral Rewards</span><br/>
                      <span className="min-6">
                      For sharing NRGY DeFi Financial System
                      </span>
                    </div>
                  </div>
                  <div className="p-btn-3">
                    <button class="btn  btn-get-nrgy-3" type="submit">
                      <span className="N2N-font">GET $NRGYGO</span>
                    </button>
                
                    <div class="position-absolute end-0">
                <img className="" src={ETHEREUM} alt="" />
              </div>
            
                    </div>
                 
              
                 
                </div>
               
              </div>
              <div class="position-absolute start-0">
            <img className="" src={Ellipse180} alt="" />
          </div>
                  <span className="total-supply">Total Supply - 4.300.000</span>
            </div>

            <div className="col-2 col-xs-2">
              <div class="position-absolute end-0">
                <img className="" src={NRGY} alt="" />
              </div>
            </div>
            <div className="col-4 col-xs-6">
              <div>
                <span className="N2N-span-1">
                  NRGYGO on BINANCE SMART
                  <br /> CHAIN
                </span>
                <br />
                {/* choti ball */}
                <div class="position-absolute start-0">
                <img className="" src={Elli346} alt="" />
              </div>
                <span className="N2N-span-3">
                  NRGYGO coin on binance smart chain is our new
                  <br /> low-cost transactional coin designed to provide
                  <br />
                  convebience for DAPP consumers while producting
                  <br />
                  long-term prepetual rewards for the NRGY economy.
                </span>
                <br />

                <span className="N2N-span-3">
                  NRGYGO provides great opportunities for crypto
                  <br /> investors throught trading and new income
                  <br />
                  opportunities for the NRGY community throught shared
                  <br />
                  free rewards.
                </span>
                <br />
                <span className="N2N-span-3">NRGYGO Convensions:</span>
                <br />
              </div>
                <span className="N2N-span-3">1,000,000 NRGYGO = 1 NRGY</span>
                <div class="position-absolute end-0">
            <img className="elli-344-ikm" src={Elli344} alt="" />
          </div>
              <div className="container-5">
                <div className="card bg-N2N2">
                  <div className="row">
                    <span className="min-5">Coin Holder Rewards</span>
                    <div className="col-4">
                      <span className="min-4">1%</span><br/>
                      <span className="min-5">Transaction Rewards</span><br/>
                      <span className="min-6">
                      For NRGYGO holders recieved in BNB & NRGYGO Coins
                      </span>
                      
                    </div>
                    <div class="position-absolute">
                      <img className="V495" src={Line26} alt="" />
                    </div>
                    <div className="col-4">
                      <span className="min-4">0.5%</span><br/>
                      <span className="min-5">NRGY Staker Rewards</span><br/>
                      <span className="min-6">
                      For NRGY stakers holding 5 coins<br/> or more received<br/> in USDC
                      </span>
                    </div>
                    <div class="position-absolute">
                      <img className="V496" src={Line26} alt="" />
                    </div>
                 
                    <div className="col-4">
                
                      <span className="min-4">0.5%</span><br/>
                      <span className="min-5">NRGY Liquidity Pool</span><br/>
                      <span className="min-6">
                      Increase liquidity of NRGY/USDC trading pair on uniswap
                      </span>
                
                    </div>
                
                
                  </div>
               
                 <div className="pt-3">
                  <button class="btn  btn-get-nrgy-3" type="submit">
                      <span className="N2N-font">GET $NRGYGO</span>
                    </button>
                    </div>
               
                </div>
                   
                
              </div>
             
            </div>
                  <span className="pt-4 total-supply">Total Supply - 10,000,000,000</span>
          </div>
        </div>
      </div>
    </>
  );
}
export default Nrgyon;
